language: node_js
script: ./travis.sh
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_cd598ac5ae96_key -iv $encrypted_cd598ac5ae96_iv
  -in sethladd-site-8958bc933793.json.enc -out sethladd-site-8958bc933793.json
  -d
